// SPDX-FileCopyrightText: 2002-2026 PCSX2 Dev Team
// SPDX-License-Identifier: GPL-3.0+
//
// Generated by tools/gen_iop_import_table.py from pcsx2/IopModuleNames.cpp.
// Do not edit by hand. Regenerate with:
//   python3 tools/gen_iop_import_table.py

#pragma once

#include "common/Pcsx2Types.h"

namespace R3000A {

struct IopImportExport {
  u16 index;
  const char* name;
};

struct IopImportModule {
  u64 packed_name;
  u16 id;
  u16 export_count;
  const IopImportExport* exports;
};

inline constexpr u16 kIopImportModuleCount = 47;
inline constexpr u16 kIopImportExportCount = 710;

static_assert(kIopImportModuleCount == 47);
static_assert(kIopImportExportCount == 710);

inline constexpr IopImportExport kIopExports_cdvdman[] = {
  {4, "sceCdInit"},
  {5, "sceCdStandby"},
  {6, "sceCdRead"},
  {7, "sceCdSeek"},
  {8, "sceCdGetError"},
  {9, "sceCdGetToc"},
  {10, "sceCdSearchFile"},
  {11, "sceCdSync"},
  {12, "sceCdGetDiskType"},
  {13, "sceCdDiskReady"},
  {14, "sceCdTrayReq"},
  {15, "sceCdStop"},
  {16, "sceCdPosToInt"},
  {17, "sceCdIntToPos"},
  {21, "sceCdCheckCmd"},
  {22, "_sceCdRI"},
  {24, "sceCdReadClock"},
  {28, "sceCdStatus"},
  {29, "sceCdApplySCmd"},
  {37, "sceCdCallback"},
  {38, "sceCdPause"},
  {39, "sceCdBreak"},
  {40, "sceCdReadCDDA"},
  {44, "sceCdGetReadPos"},
  {45, "sceCdCtrlADout"},
  {46, "sceCdNop"},
  {47, "_sceGetFsvRbuf"},
  {48, "_sceCdstm0Cb"},
  {49, "_sceCdstm1Cb"},
  {50, "_sceCdSC"},
  {51, "_sceCdRC"},
  {54, "sceCdApplyNCmd"},
  {56, "sceCdStInit"},
  {57, "sceCdStRead"},
  {58, "sceCdStSeek"},
  {59, "sceCdStStart"},
  {60, "sceCdStStat"},
  {61, "sceCdStStop"},
  {62, "sceCdRead0"},
  {63, "_sceCdRV"},
  {64, "_sceCdRM"},
  {66, "sceCdReadChain"},
  {67, "sceCdStPause"},
  {68, "sceCdStResume"},
  {74, "sceCdPowerOff"},
  {75, "sceCdMmode"},
  {77, "sceCdStSeekF"},
  {78, "sceCdPOffCallback"},
  {81, "_sceCdSetTimeout"},
  {83, "sceCdReadDvdDualInfo"},
  {84, "sceCdLayerSearchFile"},
  {112, "sceCdApplySCmd2"},
  {114, "_sceCdRE"},
};

inline constexpr IopImportExport kIopExports_deci2api[] = {
  {4, "sceDeci2Open"},
  {5, "sceDeci2Close"},
  {6, "sceDeci2ExRecv"},
  {7, "sceDeci2ExSend"},
  {8, "sceDeci2ReqSend"},
  {9, "sceDeci2ExReqSend"},
  {10, "sceDeci2ExLock"},
  {11, "sceDeci2ExUnLock"},
  {12, "sceDeci2ExPanic"},
  {13, "sceDeci2Poll"},
  {14, "sceDeci2ExPoll"},
  {15, "sceDeci2ExRecvSuspend"},
  {16, "sceDeci2ExRecvUnSuspend"},
  {17, "sceDeci2ExWakeupThread"},
  {18, "sceDeci2ExSignalSema"},
  {19, "sceDeci2ExSetEventFlag"},
};

inline constexpr IopImportExport kIopExports_eenetctl[] = {
  {4, "sceEENetCtlSetConfiguration"},
  {5, "sceEENetCtlRegisterDialCnf"},
  {6, "sceEENetCtlUnRegisterDialCnf"},
  {7, "sceEENetCtlSetDialingData"},
  {8, "sceEENetCtlClearDialingData"},
};

inline constexpr IopImportExport kIopExports_ent_devm[] = {
  {4, "sceEENetDevAttach"},
  {5, "sceEENetDevReady"},
  {6, "sceEENetDevDetach"},
  {7, "sceEENetSifAddCmdHandler"},
  {8, "sceEENetSifRemoveCmdHandler"},
  {9, "sceEENetSifSendCmd"},
  {10, "sceEENetSifBindRpc"},
  {11, "sceEENetSifCallRpc"},
  {12, "sceEENetCheckWaitingDriverList"},
  {13, "sceEENetCheckTerminatedDriverList"},
};

inline constexpr IopImportExport kIopExports_excepman[] = {
  {4, "RegisterExceptionHandler"},
  {5, "RegisterPriorityExceptionHandler"},
  {6, "RegisterDefaultExceptionHandler"},
  {7, "ReleaseExceptionHandler"},
  {8, "ReleaseDefaultExceptionHandler"},
};

inline constexpr IopImportExport kIopExports_heaplib[] = {
  {4, "CreateHeap"},
  {5, "DeleteHeap"},
  {6, "AllocHeapMemory"},
  {7, "FreeHeapMemory"},
  {8, "HeapTotalFreeSize"},
};

inline constexpr IopImportExport kIopExports_ilink[] = {
  {0, "sce1394SetupModule"},
  {2, "sce1394ReleaseModule"},
  {4, "sce1394Initialize"},
  {5, "sce1394Destroy"},
  {6, "sce1394Debug"},
  {7, "sce1394ConfGet"},
  {8, "sce1394ConfSet"},
  {9, "sce1394ChangeThreadPriority"},
  {12, "sce1394UnitAdd"},
  {13, "sce1394UnitDelete"},
  {17, "sce1394GenerateCrc32"},
  {18, "sce1394GenerateCrc16"},
  {19, "sce1394ValidateCrc16"},
  {23, "sce1394SbControl"},
  {24, "sce1394SbEnable"},
  {25, "sce1394SbDisable"},
  {26, "sce1394SbReset"},
  {27, "sce1394SbEui64"},
  {28, "sce1394SbNodeId"},
  {29, "sce1394SbNodeCount"},
  {30, "sce1394SbSelfId"},
  {31, "sce1394SbGenNumber"},
  {32, "sce1394SbPhyPacket"},
  {33, "sce1394SbCycleTime"},
  {36, "sce1394EvAlloc"},
  {37, "sce1394EvFree"},
  {38, "sce1394EvWait"},
  {39, "sce1394EvPoll"},
  {43, "sce1394PbAlloc"},
  {44, "sce1394PbFree"},
  {45, "sce1394PbGet"},
  {46, "sce1394PbSet"},
  {50, "sce1394TrDataInd"},
  {51, "sce1394TrDataUnInd"},
  {55, "sce1394TrAlloc"},
  {56, "sce1394TrFree"},
  {57, "sce1394TrGet"},
  {58, "sce1394TrSet"},
  {59, "sce1394TrWrite"},
  {60, "sce1394TrWriteV"},
  {61, "sce1394TrRead"},
  {62, "sce1394TrReadV"},
  {63, "sce1394TrLock"},
  {67, "sce1394CrEui64"},
  {68, "sce1394CrGenNumber"},
  {69, "sce1394CrMaxRec"},
  {70, "sce1394CrMaxSpeed"},
  {71, "sce1394CrRead"},
  {72, "sce1394CrCapability"},
  {73, "sce1394CrFindNode"},
  {74, "sce1394CrFindUnit"},
  {75, "sce1394CrInvalidate"},
};

inline constexpr IopImportExport kIopExports_ilsocket[] = {
  {0, "sceILsockModuleInit"},
  {2, "sceILsockModuleReset"},
  {4, "sceILsockInit"},
  {5, "sceILsockReset"},
  {8, "sceILsockOpen"},
  {9, "sceILsockClose"},
  {10, "sceILsockBind"},
  {11, "sceILsockConnect"},
  {12, "sceILsockSend"},
  {13, "sceILsockSendTo"},
  {14, "sceILsockRecv"},
  {15, "sceILsockRecvFrom"},
  {18, "sceILsockHtoNl"},
  {19, "sceILsockHtoNs"},
  {20, "sceILsockNtoHl"},
  {21, "sceILsockNtoHs"},
  {22, "sce1394GetCycleTimeV"},
};

inline constexpr IopImportExport kIopExports_inet[] = {
  {4, "sceInetName2Address"},
  {5, "sceInetAddress2String"},
  {6, "sceInetCreate"},
  {7, "sceInetOpen"},
  {8, "sceInetClose"},
  {9, "sceInetRecv"},
  {10, "sceInetSend"},
  {11, "sceInetAbort"},
  {12, "sceInetRecvFrom"},
  {13, "sceInetSendTo"},
  {14, "sceInetAddress2Name"},
  {15, "sceInetControl"},
  {16, "sceInetPoll"},
  {17, "sceInetNtohs"},
  {18, "sceInetHtons"},
  {19, "sceInetNtohl"},
  {20, "sceInetHtonl"},
  {21, "sceInetGet4u"},
  {22, "sceInetPut4u"},
  {24, "sceInetGetInterfaceList"},
  {25, "sceInetInterfaceControl"},
  {27, "sceInetGetRoutingTable"},
  {28, "sceInetAddRouting"},
  {29, "sceInetDelRouting"},
  {30, "sceInetGetNameServers"},
  {31, "sceInetAddNameServer"},
  {32, "sceInetDelNameServer"},
  {36, "sceInetChangeThreadPriority"},
  {38, "sceInetGetLog"},
  {39, "sceInetWaitInterfaceEvent"},
  {40, "sceInetSignalInterfaceEvent"},
  {41, "sceInetAbortLog"},
};

inline constexpr IopImportExport kIopExports_inetctl[] = {
  {4, "sceInetCtlSetConfiguration"},
  {5, "sceInetCtlUpInterface"},
  {6, "sceInetCtlDownInterface"},
  {7, "sceInetCtlSetAutoMode"},
  {8, "sceInetCtlRegisterEventHandler"},
  {9, "sceInetCtlUnregisterEventHandler"},
  {10, "sceInetCtlGetState"},
  {11, "sceInetCtlGetConfiguration"},
  {12, "sceInetCtlSetDialingData"},
  {13, "sceInetCtlClearDialingData"},
};

inline constexpr IopImportExport kIopExports_intrman[] = {
  {4, "RegisterIntrHandler"},
  {5, "ReleaseIntrHandler"},
  {6, "EnableIntr"},
  {7, "DisableIntr"},
  {8, "CpuDisableIntr"},
  {9, "CpuEnableIntr"},
  {17, "CpuSuspendIntr"},
  {18, "CpuResumeIntr"},
  {23, "QueryIntrContext"},
  {24, "QueryIntrStack"},
  {25, "iCatchMultiIntr"},
};

inline constexpr IopImportExport kIopExports_ioman[] = {
  {4, "open"},
  {5, "close"},
  {6, "read"},
  {7, "write"},
  {8, "lseek"},
  {9, "ioctl"},
  {10, "remove"},
  {11, "mkdir"},
  {12, "rmdir"},
  {13, "dopen"},
  {14, "dclose"},
  {15, "dread"},
  {16, "getstat"},
  {17, "chstat"},
  {18, "format"},
  {20, "AddDrv"},
  {21, "DelDrv"},
  {23, "StdioInit"},
  {25, "rename"},
  {26, "chdir"},
  {27, "sync"},
  {28, "mount"},
  {29, "umount"},
  {30, "lseek64"},
  {31, "devctl"},
  {32, "symlink"},
  {33, "readlink"},
  {34, "ioctl2"},
};

inline constexpr IopImportExport kIopExports_libsd[] = {
  {2, "sceSdQuit"},
  {4, "sceSdInit"},
  {5, "sceSdSetParam"},
  {6, "sceSdGetParam"},
  {7, "sceSdSetSwitch"},
  {8, "sceSdGetSwitch"},
  {9, "sceSdSetAddr"},
  {10, "sceSdGetAddr"},
  {11, "sceSdSetCoreAttr"},
  {12, "sceSdGetCoreAttr"},
  {13, "sceSdNote2Pitch"},
  {14, "sceSdPitch2Note"},
  {15, "sceSdProcBatch"},
  {16, "sceSdProcBatchEx"},
  {17, "sceSdVoiceTrans"},
  {18, "sceSdBlockTrans"},
  {19, "sceSdVoiceTransStatus"},
  {20, "sceSdBlockTransStatus"},
  {21, "sceSdSetTransCallback"},
  {22, "sceSdSetIRQCallback"},
  {23, "sceSdSetEffectAttr"},
  {24, "sceSdGetEffectAttr"},
  {25, "sceSdClearEffectWorkArea"},
  {26, "sceSdSetTransIntrHandler"},
  {27, "sceSdSetSpu2IntrHandler"},
  {28, "sceSdGetTransIntrHandlerArgument"},
  {29, "sceSdGetSpu2IntrHandlerArgument"},
  {30, "sceSdStopTrans"},
  {31, "sceSdCleanEffectWorkArea"},
  {32, "sceSdSetEffectMode"},
  {33, "sceSdSetEffectModeParams"},
};

inline constexpr IopImportExport kIopExports_loadcore[] = {
  {4, "FlushIcache"},
  {5, "FlushDcache"},
  {6, "RegisterLibraryEntries"},
  {7, "ReleaseLibraryEntries"},
  {10, "RegisterNonAutoLinkEntries"},
  {11, "QueryLibraryEntryTable"},
  {12, "QueryBootMode"},
  {13, "RegisterBootMode"},
  {27, "SetRebootTimeLibraryHandlingMode"},
};

inline constexpr IopImportExport kIopExports_moddelay[] = {
  {4, "sceMidiDelay_Init"},
  {5, "sceMidiDelay_ATick"},
  {6, "sceMidiDelay_Flush"},
};

inline constexpr IopImportExport kIopExports_modem[] = {
  {4, "sceModemRegisterDevice"},
  {5, "sceModemUnregisterDevice"},
};

inline constexpr IopImportExport kIopExports_modhsyn[] = {
  {4, "sceHSyn_Init"},
  {5, "sceHSyn_ATick"},
  {6, "sceHSyn_Load"},
  {7, "sceHSyn_VoiceTrans"},
  {8, "sceHSyn_SetReservVoice"},
  {9, "sceHSyn_SetEffectAttr"},
  {10, "sceHSyn_SetVolume"},
  {11, "sceHSyn_GetVolume"},
  {12, "sceHSyn_AllNoteOff"},
  {13, "sceHSyn_AllSoundOff"},
  {14, "sceHSyn_ResetAllControler"},
  {15, "sceHSyn_SetVoiceStatBuffer"},
  {16, "sceHSyn_SetDebugInfoBuffer"},
  {17, "sceHSyn_GetChStat"},
  {18, "sceHSyn_SetOutputMode"},
  {19, "sceHSyn_SESetMaxVoices"},
  {20, "sceHSyn_SEAllNoteOff"},
  {21, "sceHSyn_SEAllSoundOff"},
  {22, "sceHSyn_SERetrieveVoiceNumberByID"},
  {23, "sceHSyn_MSGetVoiceStateByID"},
  {24, "sceHSyn_MSGetVoiceEnvelopeByID"},
  {25, "sceHSyn_SERetrieveAllSEMsgIDs"},
  {26, "sceHSyn_GetReservVoice"},
  {27, "sceHSyn_GetOutputMode"},
  {28, "sceHSyn_Unload"},
};

inline constexpr IopImportExport kIopExports_modload[] = {
  {4, "ReBootStart"},
  {5, "LoadModuleAddress"},
  {6, "LoadModule"},
  {7, "LoadStartModule"},
  {8, "StartModule"},
  {9, "LoadModuleBufferAddress"},
  {10, "LoadModuleBuffer"},
  {16, "GetModuleIdList"},
  {17, "ReferModuleStatus"},
  {18, "GetModuleIdListByName"},
  {19, "LoadModuleWithOption"},
  {20, "StopModule"},
  {21, "UnloadModule"},
  {22, "SearchModuleByName"},
  {23, "SearchModuleByAddress"},
  {26, "SelfStopModule"},
  {27, "SelfUnloadModule"},
  {28, "AllocLoadMemory"},
  {29, "FreeLoadMemory"},
  {30, "SetModuleFlags"},
};

inline constexpr IopImportExport kIopExports_modmidi[] = {
  {4, "sceMidi_Init"},
  {5, "sceMidi_ATick"},
  {6, "sceMidi_Load"},
  {7, "sceMidi_SelectSong"},
  {8, "sceMidi_SongPlaySwitch"},
  {9, "sceMidi_SongSetVolume"},
  {10, "sceMidi_SongVolumeChange"},
  {11, "sceMidi_SongSetAbsoluteTempo"},
  {12, "sceMidi_SongSetRelativeTempo"},
  {13, "sceMidi_SongSetLocation"},
  {14, "sceMidi_SelectMidi"},
  {15, "sceMidi_MidiPlaySwitch"},
  {16, "sceMidi_MidiSetLocation"},
  {17, "sceMidi_MidiSetVolume"},
  {18, "sceMidi_MidiVolumeChange"},
  {19, "sceMidi_MidiSetAbsoluteTempo"},
  {20, "sceMidi_MidiGetAbsoluteTempo"},
  {21, "sceMidi_MidiSetRelativeTempo"},
  {22, "sceMidi_MidiGetRelativeTempo"},
  {23, "sceMidi_MidiSetUSecTempo"},
  {24, "sceMidi_MidiGetUSecTempo"},
  {25, "sceMidi_Unload"},
};

inline constexpr IopImportExport kIopExports_modmono[] = {
  {4, "sceMidiMono_Init"},
  {5, "sceMidiMono_ATick"},
  {6, "sceMidiMono_SetMono"},
};

inline constexpr IopImportExport kIopExports_modmsin[] = {
  {4, "sceMSIn_Init"},
  {5, "sceMSIn_ATick"},
  {6, "sceMSIn_Load"},
  {7, "sceMSIn_PutMsg"},
  {8, "sceMSIn_PutExcMsg"},
  {9, "sceMSIn_PutHsMsg"},
};

inline constexpr IopImportExport kIopExports_modsein[] = {
  {4, "sceSEIn_Init"},
  {5, "sceSEIn_ATick"},
  {6, "sceSEIn_Load"},
  {7, "sceSEIn_PutMsg"},
  {8, "sceSEIn_PutSEMsg"},
  {9, "sceSEIn_MakeNoteOn"},
  {10, "sceSEIn_MakePitchOn"},
  {11, "sceSEIn_MakeTimeVolume"},
  {12, "sceSEIn_MakeTimePanpot"},
  {13, "sceSEIn_MakeTimePitch"},
  {14, "sceSEIn_MakePitchLFO"},
  {15, "sceSEIn_MakeAmpLFO"},
  {16, "sceSEIn_MakeAllNoteOff"},
  {17, "sceSEIn_MakeAllNoteOffMask"},
  {18, "sceSEIn_MakeNoteOnZero"},
  {19, "sceSEIn_MakePitchOnZero"},
};

inline constexpr IopImportExport kIopExports_modsesq[] = {
  {4, "sceSESq_Init"},
  {5, "sceSESq_ATick"},
  {6, "sceSESq_Load"},
  {7, "sceSESq_SelectSeq"},
  {8, "sceSESq_UnselectSeq"},
  {9, "sceSESq_SeqPlaySwitch"},
  {10, "sceSESq_SeqGetStatus"},
  {11, "sceSESq_SeqIsInPlay"},
  {12, "sceSESq_SeqIsDataEnd"},
  {13, "sceSESq_SeqSetSEMsgID"},
  {14, "sceSESq_SeqTerminateVoice"},
};

inline constexpr IopImportExport kIopExports_modssyn[] = {
  {4, "sceSSyn_Init"},
  {5, "sceSSyn_ATick"},
  {6, "sceSSyn_Load"},
};

inline constexpr IopImportExport kIopExports_msifrpc[] = {
  {4, "sceSifMInitRpc"},
  {16, "sceSifMTermRpc"},
  {17, "sceSifMEntryLoop"},
};

inline constexpr IopImportExport kIopExports_netcnf[] = {
  {4, "sceNetCnfGetCount"},
  {5, "sceNetCnfGetList"},
  {6, "sceNetCnfLoadEntry"},
  {7, "sceNetCnfAddEntry"},
  {8, "sceNetCnfDeleteEntry"},
  {9, "sceNetCnfSetLatestEntry"},
  {10, "sceNetCnfAllocMem"},
  {11, "sceNetCnfInitIFC"},
  {12, "sceNetCnfLoadConf"},
  {13, "sceNetCnfLoadDial"},
  {14, "sceNetCnfMergeConf"},
  {15, "sceNetCnfName2Address"},
  {16, "sceNetCnfAddress2String"},
  {17, "sceNetCnfEditEntry"},
  {18, "sceNetCnfDeleteAll"},
  {19, "sceNetCnfCheckCapacity"},
  {20, "sceNetCnfConvA2S"},
  {21, "sceNetCnfConvS2A"},
  {22, "sceNetCnfCheckSpecialProvider"},
  {23, "sceNetCnfSetCallback"},
};

inline constexpr IopImportExport kIopExports_netdev[] = {
  {4, "sceInetRegisterNetDevice"},
  {5, "sceInetUnregisterNetDevice"},
  {6, "sceInetAllocMem"},
  {7, "sceInetFreeMem"},
  {8, "sceInetPktEnQ"},
  {9, "sceInetPktDeQ"},
  {10, "sceInetRand"},
  {11, "sceInetPrintf"},
  {12, "sceInetAllocPkt"},
  {13, "sceInetFreePkt"},
  {14, "sceInetRegisterPPPoE"},
  {15, "sceInetUnregisterPPPoE"},
};

inline constexpr IopImportExport kIopExports_scrtpad[] = {
  {4, "AllocScratchPad"},
  {5, "FreeScratchPad"},
};

inline constexpr IopImportExport kIopExports_sdhd[] = {
  {4, "sceSdHdGetMaxProgramNumber"},
  {5, "sceSdHdGetMaxSampleSetNumber"},
  {6, "sceSdHdGetMaxSampleNumber"},
  {7, "sceSdHdGetMaxVAGInfoNumber"},
  {8, "sceSdHdGetProgramParamAddr"},
  {9, "sceSdHdGetProgramParam"},
  {10, "sceSdHdGetSplitBlockAddr"},
  {11, "sceSdHdGetSplitBlock"},
  {12, "sceSdHdGetSampleSetParamAddr"},
  {13, "sceSdHdGetSampleSetParam"},
  {14, "sceSdHdGetSampleParamAddr"},
  {15, "sceSdHdGetSampleParam"},
  {16, "sceSdHdGetVAGInfoParamAddr"},
  {17, "sceSdHdGetVAGInfoParam"},
  {18, "sceSdHdCheckProgramNumber"},
  {19, "sceSdHdGetSplitBlockCountByNote"},
  {20, "sceSdHdGetSplitBlockAddrByNote"},
  {21, "sceSdHdGetSplitBlockByNote"},
  {22, "sceSdHdGetSampleSetParamCountByNote"},
  {23, "sceSdHdGetSampleSetParamAddrByNote"},
  {24, "sceSdHdGetSampleSetParamByNote"},
  {25, "sceSdHdGetSampleParamCountByNoteVelocity"},
  {26, "sceSdHdGetSampleParamAddrByNoteVelocity"},
  {27, "sceSdHdGetSampleParamByNoteVelocity"},
  {28, "sceSdHdGetVAGInfoParamCountByNoteVelocity"},
  {29, "sceSdHdGetVAGInfoParamAddrByNoteVelocity"},
  {30, "sceSdHdGetVAGInfoParamByNoteVelocity"},
  {31, "sceSdHdGetSampleParamCountByVelocity"},
  {32, "sceSdHdGetSampleParamAddrByVelocity"},
  {33, "sceSdHdGetSampleParamByVelocity"},
  {34, "sceSdHdGetVAGInfoParamCountByVelocity"},
  {35, "sceSdHdGetVAGInfoParamAddrByVelocity"},
  {36, "sceSdHdGetVAGInfoParamByVelocity"},
  {37, "sceSdHdGetVAGInfoParamAddrBySampleNumber"},
  {38, "sceSdHdGetVAGInfoParamBySampleNumber"},
  {39, "sceSdHdGetSplitBlockNumberBySplitNumber"},
  {40, "sceSdHdGetVAGSize"},
  {41, "sceSdHdGetSplitBlockCount"},
  {42, "sceSdHdGetMaxSplitBlockCount"},
  {43, "sceSdHdGetMaxSampleSetParamCount"},
  {44, "sceSdHdGetMaxSampleParamCount"},
  {45, "sceSdHdGetMaxVAGInfoParamCount"},
  {46, "sceSdHdModifyVelocity"},
  {47, "sceSdHdModifyVelocityLFO"},
  {48, "sceSdHdGetValidProgramNumberCount"},
  {49, "sceSdHdGetValidProgramNumber"},
  {50, "sceSdHdGetSampleNumberBySampleIndex"},
};

inline constexpr IopImportExport kIopExports_sdrdrv[] = {
  {4, "sceSdrChangeThreadPriority"},
  {5, "sceSdrSetUserCommandFunction"},
};

inline constexpr IopImportExport kIopExports_sdsq[] = {
  {4, "sceSdSqGetMaxMidiNumber"},
  {5, "sceSdSqGetMaxSongNumber"},
  {6, "sceSdSqInitMidiData"},
  {7, "sceSdSqReadMidiData"},
  {8, "sceSdSqInitSongData"},
  {9, "sceSdSqReadSongData"},
  {10, "sceSdSqGetMaxCompTableIndex"},
  {11, "sceSdSqGetCompTableOffset"},
  {12, "sceSdSqGetCompTableDataByIndex"},
  {13, "sceSdSqGetNoteOnEventByPolyKeyPress"},
  {14, "sceSdSqCopyMidiData"},
  {15, "sceSdSqCopySongData"},
};

inline constexpr IopImportExport kIopExports_sifcmd[] = {
  {4, "sceSifInitCmd"},
  {5, "sceSifExitCmd"},
  {6, "sceSifGetSreg"},
  {7, "sceSifSetSreg"},
  {8, "sceSifSetCmdBuffer"},
  {10, "sceSifAddCmdHandler"},
  {11, "sceSifRemoveCmdHandler"},
  {12, "sceSifSendCmd"},
  {13, "isceSifSendCmd"},
  {14, "sceSifInitRpc"},
  {15, "sceSifBindRpc"},
  {16, "sceSifCallRpc"},
  {17, "sceSifRegisterRpc"},
  {18, "sceSifCheckStatRpc"},
  {19, "sceSifSetRpcQueue"},
  {20, "sceSifGetNextRequest"},
  {21, "sceSifExecRequest"},
  {22, "sceSifRpcLoop"},
  {23, "sceSifGetOtherData"},
  {24, "sceSifRemoveRpc"},
  {25, "sceSifRemoveRpcQueue"},
  {28, "sceSifSendCmdIntr"},
  {29, "isceSifSendCmdIntr"},
};

inline constexpr IopImportExport kIopExports_sifman[] = {
  {5, "sceSifInit"},
  {6, "sceSifSetDChain"},
  {7, "sceSifSetDma"},
  {8, "sceSifDmaStat"},
  {29, "sceSifCheckInit"},
  {32, "sceSifSetDmaIntr"},
};

inline constexpr IopImportExport kIopExports_spucodec[] = {
  {4, "sceSpuCodecEncode"},
};

inline constexpr IopImportExport kIopExports_stdio[] = {
  {4, "printf"},
  {5, "getchar"},
  {6, "putchar"},
  {7, "puts"},
  {8, "gets"},
  {9, "fdprintf"},
  {10, "fdgetc"},
  {11, "fdputc"},
  {12, "fdputs"},
  {13, "fdgets"},
  {14, "vfdprintf"},
};

inline constexpr IopImportExport kIopExports_sysclib[] = {
  {4, "setjmp"},
  {5, "longjmp"},
  {6, "toupper"},
  {7, "tolower"},
  {8, "look_ctype_table"},
  {9, "get_ctype_table"},
  {10, "memchr"},
  {11, "memcmp"},
  {12, "memcpy"},
  {13, "memmove"},
  {14, "memset"},
  {15, "bcmp"},
  {16, "bcopy"},
  {17, "bzero"},
  {18, "prnt"},
  {19, "sprintf"},
  {20, "strcat"},
  {21, "strchr"},
  {22, "strcmp"},
  {23, "strcpy"},
  {24, "strcspn"},
  {25, "index"},
  {26, "rindex"},
  {27, "strlen"},
  {28, "strncat"},
  {29, "strncmp"},
  {30, "strncpy"},
  {31, "strpbrk"},
  {32, "strrchr"},
  {33, "strspn"},
  {34, "strstr"},
  {35, "strtok"},
  {36, "strtol"},
  {37, "atob"},
  {38, "strtoul"},
  {40, "wmemcopy"},
  {41, "wmemset"},
  {42, "vsprintf"},
  {43, "strtok_r"},
};

inline constexpr IopImportExport kIopExports_sysmem[] = {
  {4, "AllocSysMemory"},
  {5, "FreeSysMemory"},
  {6, "QueryMemSize"},
  {7, "QueryMaxFreeMemSize"},
  {8, "QueryTotalFreeMemSize"},
  {9, "QueryBlockTopAddress"},
  {10, "QueryBlockSize"},
  {14, "Kprintf"},
};

inline constexpr IopImportExport kIopExports_thbase[] = {
  {4, "CreateThread"},
  {5, "DeleteThread"},
  {6, "StartThread"},
  {7, "StartThreadArgs"},
  {8, "ExitThread"},
  {9, "ExitDeleteThread"},
  {10, "TerminateThread"},
  {11, "iTerminateThread"},
  {12, "DisableDispatchThread"},
  {13, "EnableDispatchThread"},
  {14, "ChangeThreadPriority"},
  {15, "iChangeThreadPriority"},
  {16, "RotateThreadReadyQueue"},
  {17, "iRotateThreadReadyQueue"},
  {18, "ReleaseWaitThread"},
  {19, "iReleaseWaitThread"},
  {20, "GetThreadId"},
  {21, "CheckThreadStack"},
  {22, "ReferThreadStatus"},
  {23, "iReferThreadStatus"},
  {24, "SleepThread"},
  {25, "WakeupThread"},
  {26, "iWakeupThread"},
  {27, "CancelWakeupThread"},
  {28, "iCancelWakeupThread"},
  {29, "SuspendThread"},
  {30, "iSuspendThread"},
  {31, "ResumeThread"},
  {32, "iResumeThread"},
  {33, "DelayThread"},
  {34, "GetSystemTime"},
  {35, "SetAlarm"},
  {36, "iSetAlarm"},
  {37, "CancelAlarm"},
  {38, "iCancelAlarm"},
  {39, "USec2SysClock"},
  {40, "SysClock2USec"},
  {41, "GetSystemStatusFlag"},
  {42, "GetThreadCurrentPriority"},
  {43, "GetSystemTimeLow"},
  {44, "ReferSystemStatus"},
  {45, "ReferThreadRunStatus"},
  {46, "GetThreadStackFreeSize"},
  {47, "GetThreadmanIdList"},
};

inline constexpr IopImportExport kIopExports_thevent[] = {
  {4, "CreateEventFlag"},
  {5, "DeleteEventFlag"},
  {6, "SetEventFlag"},
  {7, "iSetEventFlag"},
  {8, "ClearEventFlag"},
  {9, "iClearEventFlag"},
  {10, "WaitEventFlag"},
  {11, "PollEventFlag"},
  {13, "ReferEventFlagStatus"},
  {14, "iReferEventFlagStatus"},
};

inline constexpr IopImportExport kIopExports_thfpool[] = {
  {4, "CreateFpl"},
  {5, "DeleteFpl"},
  {6, "AllocateFpl"},
  {7, "pAllocateFpl"},
  {8, "ipAllocateFpl"},
  {9, "FreeFpl"},
  {11, "ReferFplStatus"},
  {12, "iReferFplStatus"},
};

inline constexpr IopImportExport kIopExports_thmsgbx[] = {
  {4, "CreateMbx"},
  {5, "DeleteMbx"},
  {6, "SendMbx"},
  {7, "iSendMbx"},
  {8, "ReceiveMbx"},
  {9, "PollMbx"},
  {11, "ReferMbxStatus"},
  {12, "iReferMbxStatus"},
};

inline constexpr IopImportExport kIopExports_thsemap[] = {
  {4, "CreateSema"},
  {5, "DeleteSema"},
  {6, "SignalSema"},
  {7, "iSignalSema"},
  {8, "WaitSema"},
  {9, "PollSema"},
  {11, "ReferSemaStatus"},
  {12, "iReferSemaStatus"},
};

inline constexpr IopImportExport kIopExports_thvpool[] = {
  {4, "CreateVpl"},
  {5, "DeleteVpl"},
  {6, "AllocateVpl"},
  {7, "pAllocateVpl"},
  {8, "ipAllocateVpl"},
  {9, "FreeVpl"},
  {11, "ReferVplStatus"},
  {12, "iReferVplStatus"},
};

inline constexpr IopImportExport kIopExports_timrman[] = {
  {4, "AllocHardTimer"},
  {5, "ReferHardTimer"},
  {6, "FreeHardTimer"},
  {7, "SetTimerMode"},
  {8, "GetTimerStatus"},
  {9, "SetTimerCounter"},
  {10, "GetTimerCounter"},
  {11, "SetTimerCompare"},
  {12, "GetTimerCompare"},
  {16, "GetHardTimerIntrCode"},
  {20, "SetTimerHandler"},
  {21, "SetOverflowHandler"},
  {22, "SetupHardTimer"},
  {23, "StartHardTimer"},
  {24, "StopHardTimer"},
};

inline constexpr IopImportExport kIopExports_usbd[] = {
  {4, "sceUsbdRegisterLdd"},
  {5, "sceUsbdUnregisterLdd"},
  {6, "sceUsbdScanStaticDescriptor"},
  {7, "sceUsbdSetPrivateData"},
  {8, "sceUsbdGetPrivateData"},
  {9, "sceUsbdOpenPipe"},
  {10, "sceUsbdClosePipe"},
  {11, "sceUsbdTransferPipe"},
  {12, "sceUsbdOpenPipeAligned"},
  {13, "sceUsbdGetDeviceLocation"},
  {16, "sceUsbdChangeThreadPriority"},
  {17, "sceUsbdGetReportDescriptor"},
  {18, "sceUsbdMultiIsochronousTransfer"},
};

inline constexpr IopImportExport kIopExports_usbmload[] = {
  {4, "sceUsbmlDisable"},
  {5, "sceUsbmlEnable"},
  {6, "sceUsbmlActivateCategory"},
  {7, "sceUsbmlInactivateCategory"},
  {8, "sceUsbmlRegisterLoadFunc"},
  {9, "sceUsbmlUnregisterLoadFunc"},
  {10, "sceUsbmlLoadConffile"},
  {11, "sceUsbmlRegisterDevice"},
  {12, "sceUsbmlChangeThreadPriority"},
};

inline constexpr IopImportExport kIopExports_vblank[] = {
  {4, "WaitVblankStart"},
  {5, "WaitVblankEnd"},
  {6, "WaitVblank"},
  {7, "WaitNonVblank"},
  {8, "RegisterVblankHandler"},
  {9, "ReleaseVblankHandler"},
};

inline constexpr IopImportModule kIopImportModulesById[] = {
  {0x006E616D64766463ULL, 0, 53, kIopExports_cdvdman}, // cdvdman
  {0x6970613269636564ULL, 1, 16, kIopExports_deci2api}, // deci2api
  {0x6C746374656E6565ULL, 2, 5, kIopExports_eenetctl}, // eenetctl
  {0x6D7665645F746E65ULL, 3, 10, kIopExports_ent_devm}, // ent_devm
  {0x6E616D7065637865ULL, 4, 5, kIopExports_excepman}, // excepman
  {0x0062696C70616568ULL, 5, 5, kIopExports_heaplib}, // heaplib
  {0x0000006B6E696C69ULL, 6, 52, kIopExports_ilink}, // ilink
  {0x74656B636F736C69ULL, 7, 17, kIopExports_ilsocket}, // ilsocket
  {0x0000000074656E69ULL, 8, 32, kIopExports_inet}, // inet
  {0x006C746374656E69ULL, 9, 10, kIopExports_inetctl}, // inetctl
  {0x006E616D72746E69ULL, 10, 11, kIopExports_intrman}, // intrman
  {0x0000006E616D6F69ULL, 11, 28, kIopExports_ioman}, // ioman
  {0x000000647362696CULL, 12, 31, kIopExports_libsd}, // libsd
  {0x65726F6364616F6CULL, 13, 9, kIopExports_loadcore}, // loadcore
  {0x79616C6564646F6DULL, 14, 3, kIopExports_moddelay}, // moddelay
  {0x0000006D65646F6DULL, 15, 2, kIopExports_modem}, // modem
  {0x006E797368646F6DULL, 16, 25, kIopExports_modhsyn}, // modhsyn
  {0x0064616F6C646F6DULL, 17, 20, kIopExports_modload}, // modload
  {0x006964696D646F6DULL, 18, 22, kIopExports_modmidi}, // modmidi
  {0x006F6E6F6D646F6DULL, 19, 3, kIopExports_modmono}, // modmono
  {0x006E69736D646F6DULL, 20, 6, kIopExports_modmsin}, // modmsin
  {0x006E696573646F6DULL, 21, 16, kIopExports_modsein}, // modsein
  {0x0071736573646F6DULL, 22, 11, kIopExports_modsesq}, // modsesq
  {0x006E797373646F6DULL, 23, 3, kIopExports_modssyn}, // modssyn
  {0x006370726669736DULL, 24, 3, kIopExports_msifrpc}, // msifrpc
  {0x0000666E6374656EULL, 25, 20, kIopExports_netcnf}, // netcnf
  {0x000076656474656EULL, 26, 12, kIopExports_netdev}, // netdev
  {0x0064617074726373ULL, 27, 2, kIopExports_scrtpad}, // scrtpad
  {0x0000000064686473ULL, 28, 47, kIopExports_sdhd}, // sdhd
  {0x0000767264726473ULL, 29, 2, kIopExports_sdrdrv}, // sdrdrv
  {0x0000000071736473ULL, 30, 12, kIopExports_sdsq}, // sdsq
  {0x0000646D63666973ULL, 31, 23, kIopExports_sifcmd}, // sifcmd
  {0x00006E616D666973ULL, 32, 6, kIopExports_sifman}, // sifman
  {0x6365646F63757073ULL, 33, 1, kIopExports_spucodec}, // spucodec
  {0x0000006F69647473ULL, 34, 11, kIopExports_stdio}, // stdio
  {0x0062696C63737973ULL, 35, 39, kIopExports_sysclib}, // sysclib
  {0x00006D656D737973ULL, 36, 8, kIopExports_sysmem}, // sysmem
  {0x0000657361626874ULL, 37, 44, kIopExports_thbase}, // thbase
  {0x00746E6576656874ULL, 38, 10, kIopExports_thevent}, // thevent
  {0x006C6F6F70666874ULL, 39, 8, kIopExports_thfpool}, // thfpool
  {0x00786267736D6874ULL, 40, 8, kIopExports_thmsgbx}, // thmsgbx
  {0x0070616D65736874ULL, 41, 8, kIopExports_thsemap}, // thsemap
  {0x006C6F6F70766874ULL, 42, 8, kIopExports_thvpool}, // thvpool
  {0x006E616D726D6974ULL, 43, 15, kIopExports_timrman}, // timrman
  {0x0000000064627375ULL, 44, 13, kIopExports_usbd}, // usbd
  {0x64616F6C6D627375ULL, 45, 9, kIopExports_usbmload}, // usbmload
  {0x00006B6E616C6276ULL, 46, 6, kIopExports_vblank}, // vblank
};

inline constexpr IopImportModule kIopImportModulesByKey[] = {
  {0x0000000064627375ULL, 44, 13, kIopExports_usbd}, // usbd
  {0x0000000064686473ULL, 28, 47, kIopExports_sdhd}, // sdhd
  {0x0000000071736473ULL, 30, 12, kIopExports_sdsq}, // sdsq
  {0x0000000074656E69ULL, 8, 32, kIopExports_inet}, // inet
  {0x000000647362696CULL, 12, 31, kIopExports_libsd}, // libsd
  {0x0000006B6E696C69ULL, 6, 52, kIopExports_ilink}, // ilink
  {0x0000006D65646F6DULL, 15, 2, kIopExports_modem}, // modem
  {0x0000006E616D6F69ULL, 11, 28, kIopExports_ioman}, // ioman
  {0x0000006F69647473ULL, 34, 11, kIopExports_stdio}, // stdio
  {0x0000646D63666973ULL, 31, 23, kIopExports_sifcmd}, // sifcmd
  {0x0000657361626874ULL, 37, 44, kIopExports_thbase}, // thbase
  {0x0000666E6374656EULL, 25, 20, kIopExports_netcnf}, // netcnf
  {0x00006B6E616C6276ULL, 46, 6, kIopExports_vblank}, // vblank
  {0x00006D656D737973ULL, 36, 8, kIopExports_sysmem}, // sysmem
  {0x00006E616D666973ULL, 32, 6, kIopExports_sifman}, // sifman
  {0x000076656474656EULL, 26, 12, kIopExports_netdev}, // netdev
  {0x0000767264726473ULL, 29, 2, kIopExports_sdrdrv}, // sdrdrv
  {0x0062696C63737973ULL, 35, 39, kIopExports_sysclib}, // sysclib
  {0x0062696C70616568ULL, 5, 5, kIopExports_heaplib}, // heaplib
  {0x006370726669736DULL, 24, 3, kIopExports_msifrpc}, // msifrpc
  {0x0064616F6C646F6DULL, 17, 20, kIopExports_modload}, // modload
  {0x0064617074726373ULL, 27, 2, kIopExports_scrtpad}, // scrtpad
  {0x006964696D646F6DULL, 18, 22, kIopExports_modmidi}, // modmidi
  {0x006C6F6F70666874ULL, 39, 8, kIopExports_thfpool}, // thfpool
  {0x006C6F6F70766874ULL, 42, 8, kIopExports_thvpool}, // thvpool
  {0x006C746374656E69ULL, 9, 10, kIopExports_inetctl}, // inetctl
  {0x006E616D64766463ULL, 0, 53, kIopExports_cdvdman}, // cdvdman
  {0x006E616D726D6974ULL, 43, 15, kIopExports_timrman}, // timrman
  {0x006E616D72746E69ULL, 10, 11, kIopExports_intrman}, // intrman
  {0x006E696573646F6DULL, 21, 16, kIopExports_modsein}, // modsein
  {0x006E69736D646F6DULL, 20, 6, kIopExports_modmsin}, // modmsin
  {0x006E797368646F6DULL, 16, 25, kIopExports_modhsyn}, // modhsyn
  {0x006E797373646F6DULL, 23, 3, kIopExports_modssyn}, // modssyn
  {0x006F6E6F6D646F6DULL, 19, 3, kIopExports_modmono}, // modmono
  {0x0070616D65736874ULL, 41, 8, kIopExports_thsemap}, // thsemap
  {0x0071736573646F6DULL, 22, 11, kIopExports_modsesq}, // modsesq
  {0x00746E6576656874ULL, 38, 10, kIopExports_thevent}, // thevent
  {0x00786267736D6874ULL, 40, 8, kIopExports_thmsgbx}, // thmsgbx
  {0x6365646F63757073ULL, 33, 1, kIopExports_spucodec}, // spucodec
  {0x64616F6C6D627375ULL, 45, 9, kIopExports_usbmload}, // usbmload
  {0x65726F6364616F6CULL, 13, 9, kIopExports_loadcore}, // loadcore
  {0x6970613269636564ULL, 1, 16, kIopExports_deci2api}, // deci2api
  {0x6C746374656E6565ULL, 2, 5, kIopExports_eenetctl}, // eenetctl
  {0x6D7665645F746E65ULL, 3, 10, kIopExports_ent_devm}, // ent_devm
  {0x6E616D7065637865ULL, 4, 5, kIopExports_excepman}, // excepman
  {0x74656B636F736C69ULL, 7, 17, kIopExports_ilsocket}, // ilsocket
  {0x79616C6564646F6DULL, 14, 3, kIopExports_moddelay}, // moddelay
};

} // namespace R3000A
