#!/usr/bin/env python3
"""Generate the zero-allocation IOP import lookup tables.

Parses the active MODULE/EXPORT blocks in pcsx2/IopModuleNames.cpp
(everything before the `#if 0` that disables the undocumented leftover list)
and writes pcsx2/IopImportTableData.h.

Usage, from the pcsx2 root:
    python3 tools/gen_iop_import_table.py
    python3 tools/gen_iop_import_table.py /path/to/IopModuleNames.cpp
"""

from __future__ import annotations

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DEFAULT_SRC = ROOT / "pcsx2/IopModuleNames.cpp"
OUT = ROOT / "pcsx2/IopImportTableData.h"

EXPECTED_MODULES = 47
EXPECTED_EXPORTS = 710

MODULE_RE = re.compile(r"^MODULE\((\w+)\)\s*$")
EXPORT_RE = re.compile(r"^EXPORT\(\s*(\d+)\s*,\s*([A-Za-z_]\w*)\s*\)\s*$")


def pack_name(name: str) -> int:
    raw = name.encode("ascii")
    if len(raw) > 8:
        raise SystemExit(f"module name longer than 8 bytes: {name!r}")
    key = 0
    for i, byte in enumerate(raw):
        key |= byte << (8 * i)
    return key


def parse_modules(path: pathlib.Path) -> list[tuple[str, list[tuple[int, str]]]]:
    modules: list[tuple[str, list[tuple[int, str]]]] = []
    current_name: str | None = None
    current_exports: list[tuple[int, str]] | None = None

    for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        stripped = line.strip()
        if stripped.startswith("#if 0"):
            break
        if stripped.startswith("#"):
            continue

        match = MODULE_RE.match(stripped)
        if match:
            if current_name is not None:
                raise SystemExit(
                    f"{path}:{lineno}: MODULE({match.group(1)}) while MODULE({current_name}) still open"
                )
            current_name = match.group(1)
            current_exports = []
            continue

        if stripped == "END_MODULE":
            if current_name is None or current_exports is None:
                raise SystemExit(f"{path}:{lineno}: END_MODULE without MODULE")
            modules.append((current_name, current_exports))
            current_name = None
            current_exports = None
            continue

        match = EXPORT_RE.match(stripped)
        if match:
            if current_exports is None:
                raise SystemExit(f"{path}:{lineno}: EXPORT outside MODULE")
            current_exports.append((int(match.group(1)), match.group(2)))

    if current_name is not None:
        raise SystemExit(f"{path}: MODULE({current_name}) not closed before #if 0")
    return modules


def validate(modules: list[tuple[str, list[tuple[int, str]]]]) -> int:
    names = [name for name, _ in modules]
    if len(names) != len(set(names)):
        raise SystemExit("duplicate MODULE names in the active list")

    export_count = 0
    for name, exports in modules:
        pack_name(name)
        indices = [index for index, _ in exports]
        if len(indices) != len(set(indices)):
            raise SystemExit(f"duplicate EXPORT indices in MODULE({name})")
        if not exports:
            raise SystemExit(f"MODULE({name}) has no EXPORT entries")
        export_count += len(exports)

    if len(modules) != EXPECTED_MODULES:
        raise SystemExit(
            f"expected {EXPECTED_MODULES} modules, found {len(modules)} (rebase tripwire)"
        )
    if export_count != EXPECTED_EXPORTS:
        raise SystemExit(
            f"expected {EXPECTED_EXPORTS} exports, found {export_count} (rebase tripwire)"
        )
    return export_count


def c_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def emit_header(modules: list[tuple[str, list[tuple[int, str]]]], export_count: int) -> str:
    indexed = []
    for module_id, (name, exports) in enumerate(modules):
        sorted_exports = sorted(exports, key=lambda item: item[0])
        indexed.append((module_id, name, pack_name(name), sorted_exports))

    lines = [
        "// SPDX-FileCopyrightText: 2002-2026 PCSX2 Dev Team",
        "// SPDX-License-Identifier: GPL-3.0+",
        "//",
        "// Generated by tools/gen_iop_import_table.py from pcsx2/IopModuleNames.cpp.",
        "// Do not edit by hand. Regenerate with:",
        "//   python3 tools/gen_iop_import_table.py",
        "",
        "#pragma once",
        "",
        '#include "common/Pcsx2Types.h"',
        "",
        "namespace R3000A {",
        "",
        "struct IopImportExport {",
        "  u16 index;",
        "  const char* name;",
        "};",
        "",
        "struct IopImportModule {",
        "  u64 packed_name;",
        "  u16 id;",
        "  u16 export_count;",
        "  const IopImportExport* exports;",
        "};",
        "",
        f"inline constexpr u16 kIopImportModuleCount = {len(indexed)};",
        f"inline constexpr u16 kIopImportExportCount = {export_count};",
        "",
        f"static_assert(kIopImportModuleCount == {EXPECTED_MODULES});",
        f"static_assert(kIopImportExportCount == {EXPECTED_EXPORTS});",
        "",
    ]

    for module_id, name, _packed, exports in indexed:
        lines.append(f"inline constexpr IopImportExport kIopExports_{name}[] = {{")
        for index, export_name in exports:
            lines.append(f"  {{{index}, {c_string(export_name)}}},")
        lines.append("};")
        lines.append("")

    lines.append("inline constexpr IopImportModule kIopImportModulesById[] = {")
    for module_id, name, packed, exports in indexed:
        lines.append(
            f"  {{0x{packed:016X}ULL, {module_id}, {len(exports)}, kIopExports_{name}}}, // {name}"
        )
    lines.append("};")
    lines.append("")

    by_key = sorted(indexed, key=lambda item: item[2])
    lines.append("inline constexpr IopImportModule kIopImportModulesByKey[] = {")
    for module_id, name, packed, exports in by_key:
        lines.append(
            f"  {{0x{packed:016X}ULL, {module_id}, {len(exports)}, kIopExports_{name}}}, // {name}"
        )
    lines.append("};")
    lines.append("")
    lines.append("} // namespace R3000A")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    src = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_SRC
    if not src.is_file():
        raise SystemExit(f"IopModuleNames.cpp not found: {src}")

    modules = parse_modules(src)
    export_count = validate(modules)
    with OUT.open("w", encoding="utf-8", newline="\n") as out:
        out.write(emit_header(modules, export_count))
    print(f"{len(modules)} modules, {export_count} exports -> {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
